---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ruuvi
    component: ruuvi
  name: ruuvi
  namespace: "umec"
spec:
  type: NodePort
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 31111
  selector:
    app: ruuvi

